# Theme settings
remote_theme: just-the-docs/just-the-docs
title: SHAFT Dubbing Agent Framework
description: Documentation for the Dubbing and Speech to Speech translation agents
color_scheme: dark

# Important: Add these settings
baseurl: "/SpeechlabAgentsDocs"
url: "https://shaft-foundation.github.io"

# Enable search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/shaft-foundation/SpeechlabAgentsDocs"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Navigation structure - only including pages with content
nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /docs/getting-started/
  - title: Architecture
    url: /docs/architecture/
  - title: API Reference
    url: /docs/api-reference/
  - title: Troubleshooting
    url: /docs/troubleshooting/ 